# build stage
FROM golang:1.24 AS builder

WORKDIR /project

COPY . .

RUN go env -w GOPROXY="https://goproxy.cn,direct"
RUN go mod download
RUN go mod tidy
{{- if eq .AppPkg "app" }}
RUN CGO_ENABLED=0 go build -o ./bin/main ./cmd
{{- else }}
RUN CGO_ENABLED=0 go build -o ./bin/main ./cmd/{{.AppName}}
{{- end }}

# runtime stage
FROM scratch

WORKDIR /bin

COPY --from=builder /project/bin/main .

EXPOSE 8000

ENTRYPOINT ["./main"]
CMD ["serve", "--config", "/data/config.toml"]
